=== igwtech/reactphp-servicebus/bin/config.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/config.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE config SYSTEM "config.dtd">

    <config>
    ...
    </config>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT config (registry|routes)*>
<!ATTLIST config
    hash CDATA #IMPLIED
    date CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT registry (adapter)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT adapter EMPTY>
<!ATTLIST adapter
    scheme CDATA #IMPLIED
    classname CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT routes (route)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT route (from|to|log)*>
<!ATTLIST route
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT from EMPTY>
<!ATTLIST from
    uri CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT to EMPTY>
<!ATTLIST to
    uri CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT log EMPTY>
<!ATTLIST log
    message CDATA #IMPLIED
  >

=== igwtech/reactphp-servicebus/bin/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "config.dtd">
<!--
This file configures the server
-->
<config hash="" date="">
    <registry>
        <adapter scheme="timer" classname="\Greicodex\ServiceBuz\Processors\Consumers\TimerConsumer"  />
        <adapter scheme="http-client" classname="\Greicodex\ServiceBuz\Processors\HttpClientProcessor"  />
        <adapter scheme="https-client" classname="\Greicodex\ServiceBuz\Processors\HttpClientProcessor"  />
        <adapter scheme="http-server" classname="\Greicodex\ServiceBuz\Processors\Consumers\HttpServerConsumer"  />
        <adapter scheme="https-server" classname="\Greicodex\ServiceBuz\Processors\Consumers\HttpServerConsumer"  />
        <adapter scheme="file" classname="\Greicodex\ServiceBuz\Processors\Producers\FileProducer"  />
        <adapter scheme="dir" classname="\Greicodex\ServiceBuz\Processors\Consumers\DirConsumer"  />
        <adapter scheme="queue-consumer" classname="\Greicodex\ServiceBuz\Processors\Consumers\MQConsumer"  />
        <adapter scheme="queue-producer" classname="\Greicodex\ServiceBuz\Processors\Producers\MQProducer"  />
        <adapter scheme="trace" classname="\Greicodex\ServiceBuz\Processors\TraceProcessor" />  
        <adapter scheme="http-curl" classname="\Greicodex\ServiceBuz\Processors\CurlProcessor" />
        <adapter scheme="ftp-out" classname="\Greicodex\ServiceBuz\Processors\Producers\FtpProducer" />
        <adapter scheme="smtp" classname="\Greicodex\ServiceBuz\Processors\CurlProcessor" />
        <adapter scheme="sftp" classname="\Greicodex\ServiceBuz\Processors\CurlProcessor" />
        <adapter scheme="exec" classname="\Greicodex\ServiceBuz\Processors\ExecProcessor" />
    </registry>

    
    
    <routes>
        <!-- 
        <route id="route-file">
            <from uri="dir://monitor/tmp/input?delay=0.01" />
            <to uri="http-client://127.0.0.1/test/echo.php?httpMethod=POST"/>
            <log message="got it" />
        </route>

        <route id="route-http">
            <from uri="http-server://localhost:4080/as3" />
            <to uri="http-client://echo.opera.com?httpMethod=POST" />
            <log message="got it" />
            <to uri="http-client://127.0.0.1/test/poster.php?httpMethod=POST" />
            <to uri="file:///tmp/input/?filename=javier" />
        </route>
        -->
        <!-- 
        <route id="fortune" >
            <from uri="timer://localhost/?delay=1&amp;data=" />
            <to uri="exec://localhost/?commandLine=/usr/games/fortune" />
            <to uri="queue-producer://localhost/?routingKey=outputQueue" />
            
        </route>
        -->
        
        <!-- 
        <route id="route-mqToFile">
            <from uri="queue-consumer://guest:guest@localhost/fileQueue?routingKey=javier?"></from>
            <to uri="file:///tmp/input/?filename=javier" />
        </route>
        -->
        <route id="route-fileToMq">
            <from uri="dir://localhost/tmp/input/?delay=0.01" />
            <to uri="queue-producer://localhost/?routingKey=inputQueue" />
        </route>
        <!-- 
        <route id="route-mqOnly">
            <from uri="queue-consumer://guest:guest@localhost/inputQueue"></from>
            <to uri="queue-producer://guest:guest@localhost/outBox?routingKey=outputQueue"></to>
        </route>
        <route id="route-fileToMq">
            <from uri="dir://localhost/tmp/?delay=0.01" />
            <to uri="queue-producer://localhost/outBox?routingKey=outputQueue" />
        </route>
        
        
        <route id="route-mqtimer">
            <from uri="timer://localhost/?delay=0.01" />
            <to uri="queue-producer://guest:guest@localhost/?routingKey=inputQueue"/>
        </route>
        
        
        <route id="route-httpToMq" >
            <from uri="http-server://localhost:4080/import-mq" />
            <log message="New HTTP Request IMPORT-MQ" />
            <to uri="queue-producer://guest:guest@localhost/?routingKey=inputQueue"/>
        </route>
        -->
        
        <route id="route-httpToExec" >
            <from uri="http-server://localhost:4080/import-mq" />
            <to uri="exec://localhost/tmp/input?commandLine=/usr/bin/csplit -z -f 'temp'  - /DOC.HEADER/ {*}" />
        </route>
        
        <route id="route-mqToFTP" >
            <from uri="queue-consumer://guest:guest@localhost/inputQueue" />
            <to uri="http-client://httpbin.org/ip" />
            <log uri="Server: {header[result]} \n {body}" />
            <to uri="ftp-out://javier:sprlnk2kk@ftp.datatrans-inc.com/home/javier/tmp/?filename=test{batchid}.edi" />
        </route>
       
    </routes>
    
    
</config>
